### ISSUE TITLE
[youtube][ui/ux]: Improve styles for playlist runtime section

### ISSUE THREAD

**Issue by DarhkVoyd** [enrich-platforms/toppings#1]
## Issue 
- [x] UI/UX Improvement

**Description:**
Enhance the styles for the YouTube Playlist runtime section to make it more visually appealing and modern, while ensuring it blends seamlessly with YouTube's UI.

**Expected Behavior:**
The improved styles should provide a modern and pleasing look to the Playlist Runtime Section, complementing YouTube's design.

**Current Behavior:**
Currently, the Playlist Runtime Section has a somewhat bland and uninspiring look that lacks a modern touch and could benefit from an upgrade.

**Suggestions:**
- Enhance the typography and layout for a cleaner and more organized feel.
- Ensure that the color scheme complements YouTube's overall design while adding a fresh twist.
- Consider user experience and usability to make the section more intuitive.

**Screenshots:**
![Playlist Runtime Section](https://github.com/enrich-platforms/toppings/assets/77478658/3242e9e2-c9d8-43f7-a531-81cc32e9a716)

**Additional Context:**
To get started, you can find the youtube.css file [here](https://github.com/enrich-platforms/toppings/blob/main/src/css/youtube.css).

**Comment by AmitSaha15** [comment]
@DarhkVoyd please assign me

**Comment by AmitSaha15** [comment]
@DarhkVoyd hey, I can't see the changes I make for this particular issue. Can't figure out how to bring up the runtime section in my local device.

I have gone through the CONTRIBUTING.md but didn't get the following point.
> Load the Extension: In your Chrome browser, enable developer mode in the extensions settings and load the built extension from the "build" folder. 

Can you please guide me? It would be a great help.
Thanks.

**Comment by DarhkVoyd** [comment]
Hey @AmitSaha15,

The issue you're encountering is related to the use of eval source maps in the earlier version of our project. However, we've since made improvements and addressed this problem. To resolve it, you'll need to sync your local repository with the latest changes.

**Comment by AmitSaha15** [comment]
Thanks a lot, @DarhkVoyd. It's working now.
