### ISSUE TITLE
[Documentation  Update]:  Want to add CODE_OF_CONDUCT.md and want to add contributors section in README.md 

### ISSUE THREAD

**Issue by sb-decoder** [enrich-platforms/toppings#7]
## Issue Type
- [ ] Bug Report
- [ ] Feature Request
- [ ] UI/UX Improvement
- [x] Documentation Update
- [ ] Other (Specify)

## Description
[Provide a clear and concise description of the issue or request.]

## Expected Behavior
[Describe what you expected to happen or how you expect the feature to work.]

## Current Behavior
[Explain the current behavior or what is happening that you believe is a bug.]

## Steps to Reproduce (for Bugs)
[If this is a bug report, provide steps to reproduce the issue. Include code examples or specific actions taken.]

## Screenshots (if applicable)
[If applicable, add screenshots or images to help explain the issue or request.]

## Additional Context
[Provide any additional context or information about the issue/request that may be helpful.]

## Your Environment (if relevant)
- Browser and Version:
- Toppings Version:

## Related Issues or PRs (optional)
[Link to any related issues or pull requests.]

## Suggested Fix (for Bugs)
[If you have suggestions on how to fix the issue or implement the feature, provide them here.]

**Comment by DarhkVoyd** [comment]
Hey! @sb-decoder,

Regarding the addition of the CODE_OF_CONDUCT.md file, we've intentionally chosen not to include one at this time. As for adding a contributors section in the README.md, we currently don't find the need to include one in our documentation. Our focus is on functionality and user experience improvements in the codebase.

Please keep in mind that modifications, updates, and documentation PRs are not eligible for Hacktoberfest participation as they don't directly contribute to the codebase.
