### ISSUE TITLE
[DOCS]:  Adding code of conduct to the repository.

### ISSUE THREAD

**Issue by mohitd404** [enrich-platforms/toppings#9]
## Issue Type

- [ ✅] Documentation Update

## Description
We propose adding a comprehensive Code of Conduct to our repository to ensure a safe, respectful, and inclusive environment for all contributors and users. This code will serve as a guideline for behavior, promoting diversity, reducing conflicts, and attracting a wider range of perspectives.

## Screenshots (if applicable)

![2](https://github.com/enrich-platforms/toppings/assets/146939900/ac4eab74-c06d-4696-9603-0867dcc0a053)

**Comment by mohitd404** [comment]
please assign this issue to me !

**Comment by DarhkVoyd** [comment]
Hey! @mohitd404,

Regarding the addition of the CODE_OF_CONDUCT.md file, we've intentionally chosen not to include one at this time. As for adding a contributors section in the README.md, we currently don't find the need to include one in our documentation. Our focus is on functionality and user experience improvements in the codebase.
